### ISSUE TITLE
able to tab into a "correct" field in practice screen and edit it

### ISSUE THREAD

**Issue by akurzon** [ylikhten/alpabes#1]
When you correctly populate a field on the practice page, it disables the field so you can't edit it again.

However, if you select the field immediately to the left of the disabled field and hit tab, you are able to re-enter it and continue typing. I would expect the tab to continue on past it to the next empty/incorrect character. 

![image](https://user-images.githubusercontent.com/10657895/110863210-95c26500-827d-11eb-9f18-b60898b8b56d.png)

![image](https://user-images.githubusercontent.com/10657895/110863244-a246bd80-827d-11eb-8e09-d71ebd49ee70.png)

**Comment by ylikhten** [comment]
Hi,

Thanks for posting this issue! We'll work on fixing it.

**Comment by ylikhten** [comment]
Hi,

Issue is solved.
Thanks
